version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "80:80"
  
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=yourdatabase
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
    ports:
      - "3306:3306"
